# Generated by Django 4.0.6 on 2022-07-09 03:43

from django.db import migrations

import djangobible.fields


class Migration(migrations.Migration):

    dependencies = [
        ("test_django_app", "0002_testsingleverseobject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testsingleverseobject",
            name="verse",
            field=djangobible.fields.VerseField(blank=True, null=True),
        ),
    ]
